In [1]:
import numpy as np
import pandas as pd


In [3]:
# Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
reshaped_arr=arr.reshape(2,5)
print("the numpy array containing numbers from 1 to 10 is \n ",arr)
print("the reshaped 2x5 matrix is \n",reshaped_arr)


the numpy array containing numbers from 1 to 10 is 
  [ 1  2  3  4  5  6  7  8  9 10]
the reshaped 2x5 matrix is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 
arr1=np.arange(1,21)
print("the array is\t ",arr1)
sliced_arr1=arr1[5:15]
print("\nthe extracted elements between 5thand 15th index\t",sliced_arr1)


the array is	  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

the extracted elements between 5thand 15th index	 [ 6  7  8  9 10 11 12 13 14 15]


In [7]:
#Exercise 3: (Score : 2) Create a Pandas series with the following data:
#{'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.
s=pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print("panda series\n",s)
s['pears']=4
print("\npanda series after updation\n",s)


panda series
 apples     3
bananas    2
oranges    1
dtype: int64

panda series after updation
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
#Exercise 4: (Score : 2) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
data={
    'Name':['Jo','Jithin','Ravi','Vishnu','Ali','Hina','Deepthi','Alina','Bassim','Deljo'],
    'Age':[28,27,29,28,42,37,38,27,34,36],
    'Gender':['Male','Male','Male','Male','Male','Female','Female','Female','Male','Male']
}
df=pd.DataFrame(data)
print(df)


      Name  Age  Gender
0       Jo   28    Male
1   Jithin   27    Male
2     Ravi   29    Male
3   Vishnu   28    Male
4      Ali   42    Male
5     Hina   37  Female
6  Deepthi   38  Female
7    Alina   27  Female
8   Bassim   34    Male
9    Deljo   36    Male


In [11]:
# Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. 
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

df['Occupation']=['Programmer',' Manager', 'Analyst','Programmer',' Manager','Analyst','Programmer', 'Manager', 'Analyst','Programmer']
df


Name  Age  Gender  Occupation
0       Jo   28    Male  Programmer
1   Jithin   27    Male     Manager
2     Ravi   29    Male     Analyst
3   Vishnu   28    Male  Programmer
4      Ali   42    Male     Manager
5     Hina   37  Female     Analyst
6  Deepthi   38  Female  Programmer
7    Alina   27  Female     Manager
8   Bassim   34    Male     Analyst
9    Deljo   36    Male  Programmer

In [13]:
#Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30.
age_above30=df[df['Age']>=30]

age_above30


Name  Age  Gender  Occupation
4      Ali   42    Male     Manager
5     Hina   37  Female     Analyst
6  Deepthi   38  Female  Programmer
8   Bassim   34    Male     Analyst
9    Deljo   36    Male  Programmer

In [15]:
#Exercise 7: (Score : 2) Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv('employee.csv',index=False)


In [17]:
df_from_csv=pd.read_csv('employee.csv')

print(df_from_csv)


      Name  Age  Gender  Occupation
0       Jo   28    Male  Programmer
1   Jithin   27    Male     Manager
2     Ravi   29    Male     Analyst
3   Vishnu   28    Male  Programmer
4      Ali   42    Male     Manager
5     Hina   37  Female     Analyst
6  Deepthi   38  Female  Programmer
7    Alina   27  Female     Manager
8   Bassim   34    Male     Analyst
9    Deljo   36    Male  Programmer
